[workspace]
authors = ["VioletsOleander <1377232072@qq.com>"]
channels = ["conda-forge"]
name = "mnist"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[tasks.configure]
args = [{ arg = "build_type", default = "debug" }]
cmd = "cmake --preset={{ build_type }} -B build"
description = "Configure the project using CMake"

[tasks.build]
cmd = "cmake --build build"
description = "Build the project with generated configuration files"

[tasks.run]
cmd = "./build/mnist"
description = "Run the MNIST executable"

[dependencies]
libtorch = { version = ">=2.8.0,<3", build = "*cpu*" }
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
clangxx = ">=21.1.2,<22"
lld = ">=21.1.3,<22"
libcxx-devel = ">=21.1.3,<22"
libarrow-all = ">=21.0.0,<22"
tomlplusplus = ">=3.3.0,<4"
cli11 = ">=2.5.0,<3"
opencv = ">=4.12.0,<5"

[feature.dataset.dependencies]
python = "*"

[feature.dataset.pypi-dependencies]
huggingface-hub = { version = ">=0.35.3, <0.36", extras = ["cli"] }
datasets = ">=4.2.0, <5"
pillow = ">=11.3.0, <12"

[feature.dataset.tasks]

[feature.dataset.tasks.hf-login]
cmd = "hf auth login --token $HF_TOKEN"
description = "Log in to Hugging Face using the provided token"

[feature.dataset.tasks.get-dataset]
cmd = "hf download --repo-type dataset --local-dir dataset/raw ylecun/mnist"
description = "Download the MNIST dataset from Hugging Face"
outputs = ["dataset/raw/mnist/*.parquet", "dataset/raw/.gitattributes", "dataset/raw/README.md"]

[feature.dataset.tasks.process-dataset]
cmd = "python scripts/preprocess.py"
description = "Converts the Parquet dataset to raw binary images and text labels."
depends-on = ["get-dataset"]
outputs = ["dataset/processed/*"]

[environments]
dataset = { features = ["dataset"], no-default-feature = true }
